# Site settings
title: RachBlondon
email: rachblondon@gmail.com
description: Trainee full stack JavaScript with Founders & Coders
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rachblondon.github.io" # the base hostname & protocol for your site
twitter_username: RachBlondon
github_username:  RachBlondon

# Build settings
markdown: kramdown
